### ISSUE TITLE
have you got a precompiled binary 

### ISSUE THREAD

**Issue by webciter** [novomesk/gimp-avif-plugin#1]
i can't get it to compile

**Comment by novomesk** [comment]
Time to time I compile whole GIMP with my plugin for Windows. Here is the installer:
https://github.com/novomesk/gimp-avif-plugin/releases/tag/v2.99.1.1

This plugin works only with Development GIMP 2.99, not with GIMP stable 2.10.x
Were you able to compile this devel GIMP from sources?
If yes, what specific problems did you encountered when you attempted to compile my plug-in?

The devel GIMP has different plugin API, that's why it is not compatible with older branch.

BTW, for GIMP 2.10 for Windows I have precompilled plug-in too (but is is old). I posted download link here: https://www.reddit.com/r/AV1/comments/em7yd2/avif_plugin_for_gimp/

**Comment by novomesk** [comment]
For example when I build the plugin, it looks like [this picture](https://github.com/novomesk/gimp-avif-plugin/blob/master/img/build_file-avif.png).
How does it look on your side? What error do you get? We can investigate if you want.

**Comment by webciter** [comment]
i will get a windows box, not used windows for 10 years

**Comment by novomesk** [comment]
I am closing this because I do not plan to make binary package for Linux (like Flatpak).
If there are problems with building from sources, I am willing to help.

Occasionally I will prepare Win64 installer.
