### ISSUE TITLE
Support 2.10.X?

### ISSUE THREAD

**Issue by eclipseo** [novomesk/gimp-avif-plugin#3]
Thanks for your amazing plugin, but would it be possible to make a separate branch for 2.10.X support? I don't see GIMP 3.0 coming out soon and the development branch is not packaged yet for my distro.

**Comment by novomesk** [comment]
Unfortunately GIMP 2.10 and 2.99 have quite different API and maintaining both require extra effort.
I would rather work on the goal to add AVIF support in GIMP (no matter if it is based on libavif or libheif), I think that will be better in long term.
You will find more information about the progress here: https://gitlab.gnome.org/GNOME/gimp/-/issues/2668

**Comment by eclipseo** [comment]
Thank you. I guess I'll have to write a package for Gimp 2.99 in Fedora.

**Comment by novomesk** [comment]
You will need to add very fresh versions of gegl and babl (needed by the devel GIMP). Maybe in the near future, there will be 2.99.2 ( I guess according https://gitlab.gnome.org/GNOME/gimp/-/milestones/8 ).

**Comment by eclipseo** [comment]
> You will need to add very fresh versions of gegl and babl (needed by the devel GIMP). Maybe in the near future, there will be 2.99.2 ( I guess according https://gitlab.gnome.org/GNOME/gimp/-/milestones/8 ).

Actually build it yesterday with all deps working:
https://copr.fedorainfracloud.org/coprs/eclipseo/gimp-2.99/

Now I will tackle your plugin.

**Comment by novomesk** [comment]
BTW I observed you attempted to add libavif 0.8.0 to Fedora.
libavif 0.8.0 has a new optional component **libpixbufloader-avif.so** but there were multiple crashes we fixed already in git master.
I think users won't be if they receive the buggy libpixbufloader-avif.so
I suggest to avoid building the `AVIF_BUILD_GDK_PIXBUF` in libavif 0.8.0 or to backport fixes in the [loader.c](https://github.com/AOMediaCodec/libavif/commits/master/contrib/gdk-pixbuf/loader.c) file.
In order to activate the gdk-pixbuf loader after install, it is necessary to run `gdk-pixbuf-query-loaders --update-cache`

**Comment by eclipseo** [comment]
> BTW I observed you attempted to add libavif 0.8.0 to Fedora.
> libavif 0.8.0 has a new optional component **libpixbufloader-avif.so** but there were multiple crashes we fixed already in git master.
> I think users won't be if they receive the buggy libpixbufloader-avif.so
> I suggest to avoid building the `AVIF_BUILD_GDK_PIXBUF` in libavif 0.8.0 or to backport fixes in the [loader.c](https://github.com/AOMediaCodec/libavif/commits/master/contrib/gdk-pixbuf/loader.c) file.
> In order to activate the gdk-pixbuf loader after install, it is necessary to run `gdk-pixbuf-query-loaders --update-cache`

Hey thanks, libavif was already packaged but without pixbuf. I have a PR open to update it but will take your comment  into account. I don't have GNOME so I can't really test the pixbuf thingie.
On the other hand your plugin works amazingly with GIMP 2.99!
